### ISSUE TITLE
Enable basic protocol versioning checks

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#1054]
In the protocol we have the field `protocol_version` flag in start message to notify the protocol version to sdks, but we haven't tested the checks for that yet. We should make sure SDKs reject requests with an unknown protocol version.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/sdk-java/issues/198
- [ ] https://github.com/restatedev/sdk-typescript/issues/235
- [ ] Make sure the invoker can tolerate bad `protocol_version` failures
```
