### ISSUE TITLE
Support basic state mutation in the admin api

### ISSUE THREAD

**Issue by igalshilman** [restatedev/restate#1061]
# Allow an operator (admin) to issue state mutation for a given service instance

This issue proposes a new admin API to mutate state for a given service instance, with the intention to fix-up a programming bug. Let us start with the simplest API possible, alternative APIs and extensions are not part of this issue (such as using SQL, or more elaborate mutation options like JSON patch, jq, cue-lang etc') 
In addition, let us focus for now only on JSON state objects.
For non JSON state keys, we will followup based on need.

## High level description:

* `GET /admin api path /<svc>/<key>`
Returns a JSON object with a field for every key, and it's current version.

```json
{
 "meta" : {
        "version" : "56898174"
   },
  "state": {
       "seen_count" : 0
       "last_seen_ts" : "123456789"
       "greeting" : {
              "greetings" : [ "hi" , "yo", "hello"]
        }
  }
}
```
- a meta section, is populated by the runtime, and currently contains a single numeric value that represents the current version of the entire service's state (and not an individual key)
- the state section is 

* `PUT /../<svc>/<key>`
```json
{
  "meta" : {
      "version" : "56898174"
   }
  "state" : {
          ...
   }
}
```
- This would override the current state with the provided document.
- The `meta.version` field is optional:
- - if present: the operation will succeed only if the current version matches the provided version when the command is being applied.
- - if not present: the operation will succeed
- note that this is an overwrite operation.

## Semantics with respect to a running service

If currently a key is unlocked, the mutation would be executed next. Otherwise, these operations will be enqueued to be proceed after to currently executing invocation. 

## Integration with the CLI

One idea of integrating this with a CLI would be to issue a state mutation command for a service, followed by opening a default editor (it the style of `git commit`) 

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/1079
- [ ] https://github.com/restatedev/restate/issues/1080
- [ ] https://github.com/restatedev/restate/issues/1081
- [ ] https://github.com/restatedev/restate/issues/1082
- [ ] https://github.com/restatedev/restate/issues/1132
- [ ] https://github.com/restatedev/restate/issues/1133
- [ ] https://github.com/restatedev/documentation/issues/305
```

**Comment by tillrohrmann** [comment]
> * The meta.version field is optional:
>   * if present: the operation will succeed only if the current version matches the provided version.
>   * if not present: the operation will be enqueued for processing (like an invocation)

Do I understand it correctly that the presence of the `meta.version` field decides whether the command will be immediately applied or enqueued?

**Comment by tillrohrmann** [comment]
Alrighty, thanks for the clarification. I'll update this part to make this clear.

**Comment by AhmedSoliman** [comment]
Suggestion: The SDK can encode the serialization format as part of metadata for the state store (a set of well-defined options (json, protobuf, and a `custom` for full user control).

**Comment by slinkydeveloper** [comment]
Done
