### ISSUE TITLE
Configuration infrastructure readiness for prod

### ISSUE THREAD

**Issue by AhmedSoliman** [restatedev/restate#1064]
An umbrella issue to track restate configuration changes needed to support the next phase of the service. 

High-level goals:
* Configuration hot-reload support for a subset of keys
* Decouple config layout from internal component layout.
* Multi-format support (Primarily TOML and YAML)
* Support live introspection of applied configuration via node-ctrl API
* Support for temporary override of config keys via node-ctrl API

```[tasklist]
### Tasks
- [ ] Design a structure for the config file that follows logical system design
- [ ] Allow components to read the latest loaded config keys on demand
- [ ] Allow components to watch for config updates
- [ ] Add support for TOML configuration
- [ ] Add node-ctrl APIs to introspect (read) configuration keys
```
