### ISSUE TITLE
Make Restate evolvable

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1085]
In order to make Restate evolvable w/o requiring wiping of all data, we need to add version information to all user facing resources that Restate offers and to the data we are storing. Having version information we can then start evolving these resources by introducing new versions and adding migration logic/scripts that can transform a resource from one version to another.

Resources that we need to check for evolvability:

### API endpoints 

* REST API
* Sql query endpoint

For the API endpoints we probably need to add version information to the path to make them evolvable. This can probably also be added once we introduce the next breaking change.

### Stored data

* Schema information
* Service state

For the stored data, we can store the version information as part of the data and check whether the actual version information equals the expected version information on startup. In case that it does not match, we can ask the user to run a migration script.

### Identifiers

* AwakeableIdentifier
* InvocationId
* EndpointId (aka. Deployment ID)
* Subscription ID

For the identifiers, we probably need to introduce version information which allows the runtime to understand the version of an ID when the runtime receives it.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/1086
- [ ] https://github.com/restatedev/restate/issues/1095
- [ ] https://github.com/restatedev/restate/issues/1116
- [ ] https://github.com/restatedev/restate/issues/1117
- [ ] https://github.com/restatedev/restate/issues/1118
```

### References
[1] https://docs.google.com/document/d/19Goe6bUqPhfW2Ux8yHd2HaOXjGFyWX5qLrjSFD4OY2U

**Comment by AhmedSoliman** [comment]
I don't think we should version the REST endpoints, instead, we should evolve them in a backward compatible way.

**Comment by tillrohrmann** [comment]
> I don't think we should version the REST endpoints, instead, we should evolve them in a backward compatible way.

Fine with me. If this should be for some reason not possible at some point, then we can always go the route of introducing versions later.

**Comment by tillrohrmann** [comment]
Great, then we have completed this issue :-) Thanks a lot for all the work Ahmed!
