### ISSUE TITLE
List state entries

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#1143]
Context method to list all the registered state entries for this service:

```
List<String> states = ctx.stateKeys()
```

Or something similar.
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/service-protocol/issues/66
- [ ] https://github.com/restatedev/restate/issues/1162
- [ ] https://github.com/restatedev/sdk-java/issues/218
- [ ] https://github.com/restatedev/sdk-typescript/issues/254
```
