### ISSUE TITLE
Bump protocol version to 1

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#1159]
```[tasklist]
### Tasks
- [ ] Update service-protocol to 1
- [x] Update runtime service-protocol supported version to 1
- [x] Update sdk-java supported protocol version to 1
- [x] Update sdk-typescript supported protocol version to 1
```
