### ISSUE TITLE
Service endpoint registration

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#13]
Implement automatic service endpoint registration, by scraping service schemas from service endpoints directly.

```[tasklist]
* [x] restatedev/service-protocol#12
* [ ] https://github.com/restatedev/restate/issues/156
* [ ] https://github.com/restatedev/restate/issues/159
* [ ] https://github.com/restatedev/restate/issues/44
* [x] restatedev/sdk-java#31
```
