### ISSUE TITLE
Add support for forward evolution of storage

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1317]
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/1378
- [ ] https://github.com/restatedev/restate/issues/1391
- [ ] https://github.com/restatedev/restate/issues/1410
- [ ] https://github.com/restatedev/restate/issues/1411
- [ ] https://github.com/restatedev/restate/issues/1412
- [ ] https://github.com/restatedev/restate/issues/1417
- [ ] https://github.com/restatedev/restate/issues/1477
- [x] Add headers to bifrost payload
- [ ] https://github.com/restatedev/restate/issues/1478
- [ ] https://github.com/restatedev/restate/issues/1489
```

**Comment by tillrohrmann** [comment]
Completed.
