### ISSUE TITLE
Idempotency support

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#1324]
## Semantics

The proposed semantics apply only on requests with idempotency key, meaning no behavioral/storage changes for non-idempotent requests.

User provides the idempotency key in the ingress request, as `idempotency-key` header. The key is a length bound string and must be bigger than `0`. 

The idempotency key can be attached to any request targeting a service/virtual object. The idempotency key can be attached for a regular call, for a send or a send with delay.

In case a request is sent again, the following semantics apply:

* For regular calls:
  * In case the invocation has not completed yet, it latches to the original invocation, waiting for the output
  * In case the invocation has completed, it returns the output if available, otherwise returns 410 GONE
* For send/send delayed calls, the user gets back the invocation_id

The scope of the idempotency key is on the invocation target, that is:

* For Services: Service name and handler name
* For Virtual objects: Virtual object name, virtual object key and handler name

The idempotency-key and the invocation result are stored for a retention time, that starts from the end of the invocation execution.

This timer is tunable on the service configuration using the Admin API. The default retention time is 24h.

## Implementation plan

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/pull/1326
- [ ] https://github.com/restatedev/restate/pull/1334
- [ ] https://github.com/restatedev/restate/pull/1348
- [ ] https://github.com/restatedev/restate/pull/1354
- [ ] https://github.com/restatedev/restate/pull/1355
- [ ] https://github.com/restatedev/restate/pull/1357
- [ ] https://github.com/restatedev/e2e/pull/299
- [ ] https://github.com/restatedev/restate/issues/1233
- [ ] https://github.com/restatedev/e2e/issues/208
- [ ] Override the default idempotency retention timer in the restate main configuration
```

**Comment by tillrohrmann** [comment]
The payload won't be checked for equality when receiving an already existing idempotency key, right?

**Comment by slinkydeveloper** [comment]
Yep, there won't be any equality check for the time being. We might reconsider later if we have a good solution for that.

**Comment by slinkydeveloper** [comment]
This is now fully implemented. I leave as followup _Override the default idempotency retention timer in the restate main configuration_, to be implemented only if we need to.

**Comment by tillrohrmann** [comment]
🎉  Great work @slinkydeveloper!
