### ISSUE TITLE
AWS Lambda Service endpoint support

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#14]
Support deploying service endpoints on AWS Lambda.

```[tasklist]
* [x] https://github.com/restatedev/restate/issues/83
* [x] https://github.com/restatedev/restate/issues/16
* [ ] https://github.com/restatedev/sdk-java/issues/12
* [ ] restatedev/restate#31
* [ ] restatedev/sdk-java#35
```
