### ISSUE TITLE
Complete integration of service protocol version negotiation

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1477]
To evolve the SDKs and runtime independently of each other, we need to fully integrate the service protocol version negotiation as described [here](https://docs.google.com/document/d/1QzIR5DVl4y58C_RdfSgmbjuAmk5NBm_busGcEK4c9gk). There are few tasks left to be done.

```[tasklist]
### Tasks
- [x] Validate protocol version at discovery time
- [ ] https://github.com/restatedev/restate/issues/1507
- [ ] https://github.com/restatedev/restate/issues/1510
- [x] Update service protocol to propagate service protocol version in the content type
- [x] Update SDKs to announce their supported version range and validate it on invocation time
- [ ] https://github.com/restatedev/service-protocol/issues/92
- [ ] https://github.com/restatedev/restate/issues/1523
- [ ] https://github.com/restatedev/sdk-java/issues/317
- [ ] https://github.com/restatedev/sdk-typescript/issues/356
```

**Comment by slinkydeveloper** [comment]
I'm gonna start with the protocol changes

**Comment by tillrohrmann** [comment]
Completed the service protocol version negotiation.
