### ISSUE TITLE
Invoker

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#15]
Umbrella issue for invoker component:

```[tasklist]
- [ ] https://github.com/restatedev/restate/issues/70
- [ ] https://github.com/restatedev/restate/issues/75
- [ ] https://github.com/restatedev/restate/issues/79
- [ ] https://github.com/restatedev/restate/issues/82
- [ ] https://github.com/restatedev/restate/issues/97
- [ ] https://github.com/restatedev/restate/issues/83
- [ ] https://github.com/restatedev/restate/issues/84
- [ ] https://github.com/restatedev/restate/issues/16
- [x] Test with SDK
- [ ] https://github.com/restatedev/restate/issues/76
- [ ] https://github.com/restatedev/restate/issues/222
- [ ] https://github.com/restatedev/restate/issues/275
- [ ] https://github.com/restatedev/restate/issues/285
```
