### ISSUE TITLE
Distributed Restate preview

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1675]
This is the umbrella issue for the first distributed version of Restate. 

The goal is to support a static `2f+1` node Restate cluster where killing `f` nodes won't cause downtime for the processing of invocations or loss of data. The cluster won't support membership changes. The metadata store and the cluster controller can run on a separate node with durable storage. Bonus points if the metadata store would be HA as well. It is ok if every node runs all partition processors.

Performance-wise, this version should be in the same ballpark as the single node Restate variant.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/1805
- [ ] https://github.com/restatedev/restate/issues/1799
- [ ] https://github.com/restatedev/restate/issues/1830
- [ ] https://github.com/restatedev/restate/issues/1781
- [ ] https://github.com/restatedev/restate/issues/1807
- [ ] https://github.com/restatedev/restate/issues/1801
- [ ] https://github.com/restatedev/restate/issues/1800
- [ ] https://github.com/restatedev/restate/issues/1806
- [ ] https://github.com/restatedev/restate/issues/1810
- [ ] https://github.com/restatedev/restate/issues/1815
- [ ] https://github.com/restatedev/restate/issues/1784
- [ ] https://github.com/restatedev/restate/issues/2188
- [ ] https://github.com/restatedev/restate/issues/2328
- [ ] https://github.com/restatedev/documentation/issues/507
```

**Comment by tillrohrmann** [comment]
We have completed the first version of distributed Restate 🎉

**Comment by marcus-sa** [comment]
I've been looking forward to this one
