### ISSUE TITLE
RocksDB persistence

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#17]
Umbrella issue for exploring and defining our state persistence based on RocksDB.

```[tasklist]
### Tasks
- [x] #59
- [ ] https://github.com/restatedev/restate/issues/63
- [ ] #248
- [ ] https://github.com/restatedev/restate/issues/259
- [ ] https://github.com/restatedev/restate/issues/261
- [ ] https://github.com/restatedev/restate/issues/263
- [ ] https://github.com/restatedev/restate/issues/265
- [ ] https://github.com/restatedev/restate/issues/270
```
