### ISSUE TITLE
Implement a highly available metadata store

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1784]
To make Restate fully highly available, we also need the metadata store to be highly available. We either find a kv store that provides us with linearizable reads and writes or we need to build it ourselves.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/1829
- [ ] https://github.com/restatedev/restate/issues/1831
- [ ] https://github.com/restatedev/restate/issues/1882
- [ ] https://github.com/restatedev/restate/issues/2204
- [ ] https://github.com/restatedev/restate/issues/2408
```

**Comment by tillrohrmann** [comment]
DynamoDB does not seem to work as a geo replicated highly consistent external meta data store. The problem is that there is no synchronous replication between table running in different regions (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/V2globaltables_HowItWorks.html).

**Comment by tillrohrmann** [comment]
What might work for an external metadata store is Google Cloud Spanner (not working for AWS), Azure Cosmos DB with strongest consistency settings (not working for AWS) (https://learn.microsoft.com/en-us/azure/cosmos-db/consistency-levels) or CockroachDB (https://cockroachlabs.cloud/).
