### ISSUE TITLE
Miscellaneous  follow-ups for distributed Restate

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1800]
Umbrella issue for collection various improvements related for the distributed Restate work.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/1266
- [ ] https://github.com/restatedev/restate/issues/2146
- [ ] https://github.com/restatedev/restate/issues/1312
- [ ] https://github.com/restatedev/restate/issues/1310
- [x] Metadata store requirement for bootstrap node not needed with external stores
- [ ] https://github.com/restatedev/restate/issues/2153
- [ ] https://github.com/restatedev/restate/issues/2155
- [ ] https://github.com/restatedev/restate/issues/1811
- [ ] https://github.com/restatedev/restate/issues/2276
- [ ] https://github.com/restatedev/restate/issues/2333
- [ ] https://github.com/restatedev/restate/issues/2377
- [ ] https://github.com/restatedev/restate/issues/2550
- [ ] https://github.com/restatedev/restate/issues/2552
- [ ] https://github.com/restatedev/restate/pull/2544
- [ ] https://github.com/restatedev/restate/pull/2554
- [ ] https://github.com/restatedev/restate/issues/2557
- [ ] https://github.com/restatedev/restate/issues/2561
- [ ] https://github.com/restatedev/restate/issues/2563
- [ ] https://github.com/restatedev/restate/issues/2604
```
