### ISSUE TITLE
Raft-based embedded metadata store

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1831]
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/1785
- [ ] https://github.com/restatedev/restate/issues/1791
- [ ] https://github.com/restatedev/restate/issues/1803
- [ ] https://github.com/restatedev/restate/issues/1804
- [ ] https://github.com/restatedev/restate/issues/1821
- [ ] https://github.com/restatedev/restate/issues/1822
- [ ] https://github.com/restatedev/restate/issues/1823
```
