### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#1870]
Umbrella issue for collecting ideas for possible performance improvements

```[tasklist]
### Tasks
- [ ] #1421
- [ ] #1428
- [ ] Verify usage of ByteString instead of String
- [ ] Reduce memory copies by passing structs as Box/Arc
- [ ] Zero-copy serialization
- [ ] Cache frequently accessed structures in `PartitionStore`
```
