### ISSUE TITLE
Release Restate 1.1

### ISSUE THREAD

**Issue by pcholakov** [restatedev/restate#1911]
Tracking issue for the release of Restate 1.1

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/1924
- [x] Update various SDK version compatibility matrices
- [x] Add an "Upgrading" section to the docs
- [x] Write up backup & restore instructions for restate-data state
- [x] Ad-hoc compatibility / database upgrade testing
- [x] Performance regression testing
- [x] Release updated service protocol
- [x] Create release notes
```

**Comment by pcholakov** [comment]
Ad-hoc database compatibility testing done:

- [x] Restored restate-cloud snapshot and upgraded to 1.1.0 build (0da2eb0 aarch64-unknown-linux-gnu 2024-09-04), plus revert to 1.0.2 and verify state and metadata
- [x] 24 hour soak test using the same state snapshot on EC2, sanity check logs and metrics
- [x] Same test using restate-data artifacts from e2e interpreter test

**Comment by pcholakov** [comment]
Service Protocol V2 draft release: https://github.com/restatedev/service-protocol/releases/edit/untagged-a8d48aab7f5873c17a3e

**Comment by pcholakov** [comment]
Docs update for 1.1 https://github.com/restatedev/documentation/pull/451

**Comment by pcholakov** [comment]
Upgrade and backup notes: https://github.com/restatedev/documentation/pull/452

**Comment by pcholakov** [comment]
Tagged service protocol V2: https://github.com/restatedev/service-protocol/releases/tag/v2

**Comment by pcholakov** [comment]
Published GitHub release https://github.com/restatedev/restate/releases/tag/v1.1.0 and tested a few key artifacts:

- npm restate cli and server (Mac ARM)
- Docker and npm restate-server (Linux x64)

Updated website docs with latest Java SDK.

**Comment by pcholakov** [comment]
Docs update PR merged to `main`, just need to release when ready to publish.

**Comment by pcholakov** [comment]
Announcement blog is ready to go, closing issue.
