### ISSUE TITLE
Enable cluster controller to control replicated loglet

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#2027]
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/2031
- [ ] https://github.com/restatedev/restate/issues/2078
- [ ] https://github.com/restatedev/restate/issues/2084
- [ ] https://github.com/restatedev/restate/issues/2079
- [ ] https://github.com/restatedev/restate/issues/2080
- [ ] https://github.com/restatedev/restate/issues/2081
- [ ] https://github.com/restatedev/restate/issues/2082
- [ ] https://github.com/restatedev/restate/issues/2083
- [ ] Figure out what to do when log sealing and writing new logs fail permanently
- [ ] https://github.com/restatedev/restate/issues/2086
- [ ] https://github.com/restatedev/restate/issues/2116
```
