### ISSUE TITLE
Clear all state syscall

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#224]
Syscall to clear all the state keys of this instance.

Related to restatedev/restate#223 

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/service-protocol/issues/64
- [ ] https://github.com/restatedev/restate/issues/1155
- [ ] https://github.com/restatedev/sdk-java/issues/216
- [ ] https://github.com/restatedev/sdk-typescript/issues/251
```

**Comment by slinkydeveloper** [comment]
```
ctx.clearAll()
```
