### ISSUE TITLE
SDK milestone 1A

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#24]
This is an umbrella issue for all SDK related work for the milestone 1A.

- [x] https://github.com/restatedev/sdk-java/issues/22
- [x] https://github.com/restatedev/restate/issues/13
- [x] https://github.com/restatedev/sdk-java/issues/28
- [x] #28
- [x] #33
