### ISSUE TITLE
Bootstrap embedded metadata store

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#2408]
When running an embedded metadata store, we need to bootstrap them with an initial configuration (peers of the Raft/OmniPaxos cluster). To avoid introducing a new id which users would have to configure independently of the `NodeId` and the node name, we want to reuse the `NodeId` of a node as its peer id. Since we need to write the `NodesConfiguration` to the metadata store to obtain our `NodeId`, we have a chicken-egg problem.

To solve this problem, we can introduce an explicit signal that tells one node to be the seed node of the Raft/OmniPaxos cluster. This node can create an initial `NodesConfiguration` and start the metadata store with itself as its only peer. Once this has happened, all other nodes can update the `NodesConfiguration` in the now running metadata store to obtain their node id. Later we can reconfigure the metadata store cluster to include other metadata store nodes as peers to increase its resilience.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/2411
- [ ] https://github.com/restatedev/restate/issues/2409
- [ ] https://github.com/restatedev/restate/issues/2410
- [ ] https://github.com/restatedev/restate/issues/2412
- [ ] https://github.com/restatedev/restate/issues/2414
- [ ] https://github.com/restatedev/restate/issues/2415
```
