### ISSUE TITLE
Blocking Java SDK

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#28]
Umbrella issue for all blocking Java SDK related work.

- [x] https://github.com/restatedev/sdk-java/issues/25
- [x] restatedev/sdk-java#34
- [x] https://github.com/restatedev/sdk-java/issues/26
- [x] https://github.com/restatedev/sdk-java/issues/27
- [x] https://github.com/restatedev/sdk-java/issues/30
- [x] https://github.com/restatedev/sdk-java/issues/13
- [x] https://github.com/restatedev/e2e/issues/72
