### ISSUE TITLE
Service failure semantics

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#294]
The failure semantics are defined as follows: https://github.com/restatedev/restate/issues/294#issuecomment-1582987159
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/493
- [ ] https://github.com/restatedev/restate/issues/495
- [ ] https://github.com/restatedev/sdk-typescript/issues/93
- [ ] https://github.com/restatedev/sdk-typescript/issues/99
- [ ] https://github.com/restatedev/restate/issues/619
```
