### ISSUE TITLE
Tracing

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#38]
Tracing service invocations can provide valuable insights into user programs. We could integrate with [Jaeger](https://www.jaegertracing.io/) to expose [OTEL](https://opentelemetry.io/) information.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/165
- [ ] https://github.com/restatedev/sdk-java/issues/76
- [ ] Typescript SDK tracing
```
