### ISSUE TITLE
Align on some rust conventions

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#392]
* [ ] Structured error names should be consistent. Should we call error names using `[module]Error` or simply `Error` and use qualified imports such as `[module]::Error`?
* [ ] Service names should be consistent. Should we call services using `[module]Service` or simply `Service` and use qualified imports such as `[module]::Service`? This one should probably be aligned with the error names decision.
* [x] https://github.com/restatedev/restate/issues/220
* [ ] Right now we're using common or other crates to separate api and implementation of components. This is something we're doing for meta and worker (and invoker). I think it makes sense to align on that on the same fashion of the storage, where we have `api` and `impl` crates. It probably makes sense to have them as subdirectories, e.g.

```
- storage
  - api
  - impl
- meta
  - api
  - impl
  - [.. maybe other modules ..]
- worker
  - api
  - impl
  - [.. maybe other modules ..]
```

* [x] Util crate names: `[..]_util` vs `[..]_utils`
* [x] Reconsider https://github.com/restatedev/restate/pull/166
* [x] Reconsider https://github.com/restatedev/restate/pull/242
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/542
- [ ] https://github.com/restatedev/restate/issues/546
```
