### ISSUE TITLE
Implement Meta

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#40]
Milestone 1A development tasks for the Meta component.

```[tasklist]
- [ ] https://github.com/restatedev/restate/issues/162
- [ ] #41
- [ ] #42
- [ ] #43
- [ ] https://github.com/restatedev/restate/issues/183
- [ ] https://github.com/restatedev/restate/issues/226
- [ ] https://github.com/restatedev/restate/issues/301
- [ ] https://github.com/restatedev/restate/issues/361
```
