### ISSUE TITLE
Support cancellations of ongoing invocations

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#402]
The cancellation of ongoing invocations requires finding the leaf nodes of the call hierarchy starting at the to be canceled call. Cancelling these leaf nodes will trigger the running of their compensations and then the propagation of the cancellation upwards the call hierarchy.

The tasks here reflect the design described in this document: https://docs.google.com/document/d/14s7D6KP1IKNS1K3OrVbZNKGNei9TO_-9Sk0YC5mpht8/edit?usp=sharing

```[tasklist]
### Mandatory tasks
- [ ] https://github.com/restatedev/service-protocol/issues/52
- [ ] https://github.com/restatedev/restate/issues/914
- [ ] https://github.com/restatedev/restate/issues/978
```

We also track in this umbrella some followup tasks that complete the overall picture of the cancellation feature

```[tasklist]
### Optional/followup tasks
- [ ] https://github.com/restatedev/restate/issues/917
- [ ] https://github.com/restatedev/restate/issues/827
- [ ] https://github.com/restatedev/restate/issues/924
- [ ] https://github.com/restatedev/restate/issues/979
```

**Comment by tillrohrmann** [comment]
All the mandatory tasks are completed.
