### ISSUE TITLE
Operational API

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#41]
Restate operational API is with what the user interacts to register services and to inspect service instances. You can find an API proposal [here](https://docs.google.com/document/d/1n_seWmzEWHJkd_VBJOLzjUQ6XGjmGV9MpZHwW8KAu-U/edit?usp=sharing).

```[tasklist]
- [ ] #44
- [ ] #45
- [ ] https://github.com/restatedev/restate/issues/177
- [ ] https://github.com/restatedev/restate/issues/210
- [ ] https://github.com/restatedev/restate/issues/313
- [ ] https://github.com/restatedev/restate/issues/315
```
