### ISSUE TITLE
Meta: Schema registry

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#43]
In order to store discovered service information (e.g. service descriptors) and to make this information accessible to the Restate cluster, we need a service registry that manages this information.
```[tasklist]
### Tasks
- [ ] Design the interfaces
- [ ] Investigate whether `Arc<ArcSwap>` is the right approach for data sharing (see https://github.com/restatedev/restate/issues/136)
- [ ] Implement the interfaces
- [ ] Let the meta own the write side of the registry, and pass around the interfaces for the read side of the registry
```
