### ISSUE TITLE
Eager state support

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#437]
In order to better support the AWS lambda use case, it would be important to support eager state. That way accessing state wouldn't require multiple suspensions (due to the request response protocol).

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/438
- [ ] https://github.com/restatedev/service-protocol/issues/23
- [ ] https://github.com/restatedev/restate/issues/443
- [ ] https://github.com/restatedev/sdk-typescript/issues/59
- [ ] https://github.com/restatedev/sdk-java/issues/86
- [ ] https://github.com/restatedev/e2e/pull/111
```
