### ISSUE TITLE
Improve Restate release process

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#450]
In order to generate reliable Restate releases, we need to improve our release process. The goal would be to only publish artifacts which have been properly tested. Moreover, we should make sure that our material references artifacts that are compatible with each other.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/451
- [ ] https://github.com/restatedev/restate/issues/454
- [ ] https://github.com/restatedev/sdk-typescript/issues/76
- [ ] https://github.com/restatedev/restate/issues/456
- [ ] Test release process end-to-end
- [ ] https://github.com/restatedev/restate/issues/473
- [ ] https://github.com/restatedev/restate/issues/474
```
