### ISSUE TITLE
Pin artifact versions in example material

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#451]
Depending on the latest version of the SDK and the runtime can lead to the situation that users try to combine a SDK version with an incompatible runtime just because one of them is already buffered on the local machine. Instead, we should explicitly pin the used version for the SDK and the runtime to avoid this situation. Given that the version is pinned, we need a process to update the versions upon creating a new release. We could start with having a release checklist and eventually try to automate the process.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/453
- [x] https://github.com/restatedev/restate/issues/468
- [x] Create release checklist for bumping versions
```
