### ISSUE TITLE
Implement Worker

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#46]
For milestone 1A we need to implement a basic worker with the following components:

```[tasklist]
### Necessary tasks
- [x] #9 
- [ ] #47
- [ ] #48
- [ ] https://github.com/restatedev/restate/issues/15
- [ ] #17 
- [ ] https://github.com/restatedev/restate/issues/200
- [ ] https://github.com/restatedev/restate/issues/213
```
