### ISSUE TITLE
Partition processor

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#47]
Umbrella issue for implementing the partition processor.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/22
- [ ] #56
- [ ] https://github.com/restatedev/restate/issues/64
- [ ] #69
- [ ] https://github.com/restatedev/restate/issues/72
- [ ] https://github.com/restatedev/restate/issues/86
- [ ] https://github.com/restatedev/restate/issues/93
- [ ] https://github.com/restatedev/restate/issues/125
- [ ] https://github.com/restatedev/restate/issues/137
- [ ] https://github.com/restatedev/restate/issues/146
- [ ] https://github.com/restatedev/restate/issues/147
- [ ] https://github.com/restatedev/restate/issues/148
- [ ] https://github.com/restatedev/restate/issues/165
- [ ] https://github.com/restatedev/restate/issues/195
- [ ] https://github.com/restatedev/restate/issues/223
- [ ] https://github.com/restatedev/restate/issues/272
- [ ] https://github.com/restatedev/restate/issues/276
- [ ] https://github.com/restatedev/restate/issues/287
```
