### ISSUE TITLE
Compile examples as part of the release process

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#473]
We currently have a couple of examples (https://github.com/restatedev/example-lambda-ts-greeter, https://github.com/restatedev/example-ticket-reservation-system, https://github.com/restatedev/example-shopping-cart-typescript) for which we create releases. As part of the release process we should at least try to build the user code to make sure that things are still working.

```[tasklist]
### Tasks
- [ ] Compile example-lambda-ts-greeter for release
- [ ] Compile example-ticket-reservation-system for release
- [ ] Compile example-shopping-cart-typescript for release
```

**Comment by slinkydeveloper** [comment]
Solved
