### ISSUE TITLE
Support more expressive retryable SDK errors

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#493]
We need a way to let the SDK send more expressive error messages for retryable errors back to the runtime. That way we can give our users more information about what went wrong and we can also use this information to figure out when a service is likely to be stuck in a retry loop.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/service-protocol/pull/26
- [ ] https://github.com/restatedev/restate/issues/421
- [ ] https://github.com/restatedev/restate/issues/494
- [ ] https://github.com/restatedev/sdk-typescript/issues/92
- [ ] https://github.com/restatedev/sdk-java/issues/94
```
