### ISSUE TITLE
Upgrades and versioning of Restate services

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#499]
### General idea

The general idea for supporting upgrading stateful services is to have logical service endpoints that run an immutable version of the code. The logical service endpoint is identified by an unique combination of URI and header values which are explicitly registered at Restate. When the registration happens, Restate will contact the logical service endpoint under the specified coordinates to discover the services. It is important to note that multiple logical endpoints could run on the same physical machine (e.g. by routing requests based on the path of the URI or the header values).

When Restate starts invoking a service, the invoker will pick the latest known service version to send the request to. Once the first journal entries are being committed the chosen version must be committed as well. That way a partial journal will always have a version associated. When re-invoking such a partial invocation, the invoker will only send it to a logical endpoint of the same version. That way, Restate will make sure that users won't run into journal incompatibilities when upgrading services because a started invocation will run to completion with the same version of the code.

In order to upgrade a service, the user needs to first deploy the new version of her service. Next, she needs to explicitly register this new version at Restate. From this time onwards, new invocations will be executed by the new version of the service. In-flight invocations will be run to completion using the old service endpoint.

We expect that most invocations will complete fairly fast so that decommissioning the old service endpoint after a short delay might be feasible. In case that there are still in-flight invocations, they would have to be killed manually.

If the user knows that invocations can be safely upgraded (w/o being run to completion on the old code), we could provide a command to replace an existing version by overwriting the logical endpoint coordinates. In this case, in-flight invocations will be executed on the new code.

Later, we can think about providing more elaborate upgrade strategies such as eagerly cancelling invocations and re-executing them on the new version (only correct if partial effects can be rolled back), specifying a grace period until in-flight invocations are being cancelled (allowing most of them to complete on the old code), automatically killing in-flight invocations of old versions, etc.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/501
- [ ] https://github.com/restatedev/restate/issues/502
- [ ] https://github.com/restatedev/restate/issues/503
- [ ] https://github.com/restatedev/restate/issues/504
- [ ] https://github.com/restatedev/restate/pull/565
- [ ] https://github.com/restatedev/restate/issues/566
- [ ] https://github.com/restatedev/restate/issues/564
- [ ] https://github.com/restatedev/documentation/issues/55
- [ ] https://github.com/restatedev/restate/issues/580
- [ ] https://github.com/restatedev/restate/issues/586
- [ ] https://github.com/restatedev/restate/issues/583
- [ ] https://github.com/restatedev/restate/issues/581
```
