### ISSUE TITLE
Support external clients

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#50]
External clients need to be able to invoke Restate services. We want to support the following endpoints:

```[tasklist]
- [ ] https://github.com/restatedev/restate/issues/102
- [ ] https://github.com/restatedev/restate/issues/104
- [ ] #51
- [ ] #52
- [ ] https://github.com/restatedev/restate/issues/112
- [ ] https://github.com/restatedev/restate/issues/115
- [ ] https://github.com/restatedev/restate/issues/132
- [ ] https://github.com/restatedev/restate/issues/133
- [ ] https://github.com/restatedev/restate/issues/149
- [ ] https://github.com/restatedev/restate/issues/192
```
