### ISSUE TITLE
Support registering different service versions

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#501]
```[tasklist]
### Tasks
- [ ] Store all the previously registered endpoints, without overriding the last one
- [ ] Make sure during reload we reload previous versions of services
- [ ] Assign a unique revision number when registering an update of an existing service
- [ ] /endpoint/discover should return the revision numbers of the discovered services
```
