### ISSUE TITLE
Kafka ingress

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#674]
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/750
- [ ] https://github.com/restatedev/restate/issues/751
- [ ] https://github.com/restatedev/restate/issues/754
- [ ] https://github.com/restatedev/restate/issues/757
- [ ] https://github.com/restatedev/restate/issues/758
- [ ] https://github.com/restatedev/restate/issues/756
- [ ] https://github.com/restatedev/restate/issues/759
- [ ] https://github.com/restatedev/restate/issues/765
- [ ] https://github.com/restatedev/sdk-typescript/issues/162
- [ ] https://github.com/restatedev/e2e/issues/192
- [ ] https://github.com/restatedev/restate/issues/676
- [ ] https://github.com/restatedev/restate/issues/762
- [ ] https://github.com/restatedev/restate/issues/763
- [ ] Support multiple topics via `kafka://my-cluster/my-topic,another-topic`
- [ ] https://github.com/restatedev/restate/issues/773
```

References:
* [Guybrush design](https://docs.google.com/presentation/d/15PZDnIVJfIriV41HQtwSGijj29rNXrTti5tJiIGaMsQ/edit#slide=id.g175e33aff62_0_79)
* [Pub/Sub design](https://docs.google.com/document/d/1oCRPcVsGaNl5MJLYLu1SkqAvZuZk6_D7DtqXAULa5IU/edit)
