### ISSUE TITLE
Make awakeables completable from outside of Restate

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#677]
In order to improve ergonomics, it would be great if users could complete and reject awakeables by calling an external API (e.g. calling an endpoint on the ingress).

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/proto/issues/20
- [ ] https://github.com/restatedev/restate/issues/678
- [ ] https://github.com/restatedev/restate/issues/679
- [ ] https://github.com/restatedev/e2e/issues/187
- [ ] https://github.com/restatedev/documentation/issues/117
```
