### ISSUE TITLE
More CI automation

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#690]
We can further improve our CI automation to detect bugs automatically:

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/692
- [ ] https://github.com/restatedev/sdk-typescript/issues/152
- [ ] https://github.com/restatedev/examples/issues/10
- [ ] https://github.com/restatedev/tour-of-restate-typescript-handler/issues/1
- [ ] https://github.com/restatedev/tour-of-restate-typescript/issues/10
- [ ] https://github.com/restatedev/restate/issues/696
- [ ] https://github.com/restatedev/examples/issues/11
- [ ] https://github.com/restatedev/tour-of-restate-typescript-handler/issues/2
- [ ] https://github.com/restatedev/tour-of-restate-typescript/issues/11
- [ ] Add license header checks to restatedev/proto
- [ ] Add license header checks to restatedev/service-protocol
```
