### ISSUE TITLE
Shorten the Awakeable id

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#703]
Rather than using the combination _service name_ + _service key_ + _invocation id_ + _entry index_, we could use simply _partition key_ + _invocation id_ + _entry index_. This would make the awakeable id bounded, solving problems such as https://github.com/restatedev/proto/pull/21#discussion_r1294356433 and it would not leak the service key anymore.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/706
- [ ] https://github.com/restatedev/restate/issues/707
- [ ] https://github.com/restatedev/service-protocol/issues/46
- [ ] https://github.com/restatedev/restate/issues/721
- [ ] https://github.com/restatedev/sdk-typescript/issues/154
- [ ] https://github.com/restatedev/sdk-java/issues/107
```
