### ISSUE TITLE
Use partition_key + invocation_id as "public invocation id"

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#704]
This is a bit of an extension from https://github.com/restatedev/restate/issues/703. The idea is to use _partition key_ + _invocation id_ as the id the user sees in the logs and in the sql interface, to query invocations and to use admin commands like kill/cancel.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/713
- [ ] https://github.com/restatedev/restate/issues/725
- [ ] https://github.com/restatedev/restate/issues/726
- [ ] https://github.com/restatedev/documentation/issues/127
```
