### ISSUE TITLE
Implement ingress_rest API

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#744]
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/745
- [ ] https://github.com/restatedev/restate/issues/746
- [ ] Generate OpenAPI
- [ ] Add to documentation (including OpenAPI)
- [ ] E2E Test
```

**Comment by slinkydeveloper** [comment]
This is not relevant anymore
