### ISSUE TITLE
Idempotent invoke

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#784]
Allow a user to invoke a service idempotently, providing an idempotency id

```[tasklist]
### Tasks
- [ ] Define user-facing contract of the built-in service: https://github.com/restatedev/proto/pull/28
- [ ] Implement ServiceInvocationResponseSink::NewInvocation to send request back to a built-in service generating a new invocation
- [ ] Implement special cases of json -> protobuf and back in schema registry
- [ ] Correctly configure key extraction in schemas_impl with the Custom service instance typ
- [ ] Implement the built-in service
```
