### ISSUE TITLE
Reconsider port numbers

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#789]
Now we have a bunch of ports in restate, perhaps it's worth reconsidering their numbers.
```[tasklist]
### Tasks
- [ ] Update in runtime
- [ ] Update default port in sdk typescript
- [ ] Update default port in sdk java
- [ ] Update default ports in documentation
- [ ] Update default ports in e2e tests
- [ ] Update default ports in examples
- [ ] https://github.com/restatedev/node-template-generator/issues/14
```
