### ISSUE TITLE
Embedded Handler API

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#794]
```[tasklist]
### Tasks
- [x] Define service contract for RemoteContext service
- [ ] https://github.com/restatedev/restate/issues/796
- [ ] https://github.com/restatedev/sdk-typescript/issues/165
- [ ] https://github.com/restatedev/e2e/issues/205
```
