### ISSUE TITLE
Distributed architecture: Towards the shared log API

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#871]
This is an umbrella issue to track the work of implementing the [distributed architecture based on the shared log API](https://docs.google.com/document/d/1Or4MxaVXefR5MinlgmuxTmbbeunaM3Vggj1ESLckpb8).

```[tasklist]
### Tasks
- [ ] Create blog post about how Restate becomes distributed
- [ ] https://github.com/restatedev/restate/issues/1123
- [ ] https://github.com/restatedev/restate/issues/872
- [ ] https://github.com/restatedev/restate/issues/874
- [ ] https://github.com/restatedev/restate/issues/875
- [ ] https://github.com/restatedev/restate/issues/876
- [ ] https://github.com/restatedev/restate/issues/877
- [ ] https://github.com/restatedev/restate/issues/1122
- [ ] https://github.com/restatedev/restate/issues/1280
```

**Comment by tillrohrmann** [comment]
Superseded by #1675.
