### ISSUE TITLE
Unify user facing Restate terminology

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#897]
We want to provide a consistent terminology to our users: Current collection of ideas: https://docs.google.com/spreadsheets/d/1jgfXuZJ9wurH_nhbpGUxb335d4oD0AUZrl4WSuczwOU/edit#gid=0.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/sdk-java/issues/160
- [ ] https://github.com/restatedev/restate/issues/989
- [ ] https://github.com/restatedev/sdk-typescript/issues/229
```

**Comment by tillrohrmann** [comment]
https://www.notion.so/restatedev/Restate-Terminology-4fc64402a5594a8caa18ea78e34bce6d

**Comment by tillrohrmann** [comment]
Things to align on:

1. Service types
2. Ids 
3. Admin surface alignment
4. SDK surface alignment (e.g. oneWayCall / send)

**Comment by slinkydeveloper** [comment]
I think this can be closed now.
