### ISSUE TITLE
Size limits of user data

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#90]
We should introduce size limits for user data.

For these we should have tunable limits with reasonable defaults:

* [ ] Max state key size
* [ ] Max state value size
* [ ] Max grpc request size
* [ ] Max grpc response size
* [ ] Max awakeable completion size (probably same as max grpc request/response size?)
* [ ] Max size of custom raw entry, for side effect
* [ ] Max size of service protocol message (depending on the other limits)

We should also limit:

* [ ] Max grpc status message size. In this case we can simply truncate the message.
* [ ] Max grpc service name/service method length. In this case the service endpoint registration should fail.

**Comment by slinkydeveloper** [comment]
Shall we close this @tillrohrmann ?

**Comment by tillrohrmann** [comment]
I'd be fine closing this issue and wait for more user feedback before taking action.
