### ISSUE TITLE
Kill the complete call tree when killing an invocation

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#914]
The partition processor should implement the behavior described in this document https://docs.google.com/document/d/14s7D6KP1IKNS1K3OrVbZNKGNei9TO_-9Sk0YC5mpht8/edit#heading=h.b6opkmlzcso7, notably:

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/941
- [ ] https://github.com/restatedev/restate/issues/951
- [ ] https://github.com/restatedev/restate/issues/942
- [ ] https://github.com/restatedev/restate/issues/972
```
