### ISSUE TITLE
Make restatedev/restate public

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#921]
```[tasklist]
### Tasks
- [x] Update README to latest state
- [x] Publish restate packages
- [x] Update org README to point to restatedev/restate
- [x] Update DockerHub REAMDE to point to restatedev/restate
- [x] Search material for restate-dist and replace with restate
- [x] Archive restate-dist
```
