### ISSUE TITLE
Side effects should wait for other entries acks

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/restate#922]
This is a consequence of the cancellation proposal. See https://docs.google.com/document/d/14s7D6KP1IKNS1K3OrVbZNKGNei9TO_-9Sk0YC5mpht8/edit#heading=h.hooeo8f4d03z for more details.

To be specific, side effect should wait for acks of entries which can cause cancellations. In the first iteration of the feature, we thought about waiting for all the entries acks anyway, as we can start cancelling on any RestateContext call.

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/service-protocol/issues/53
- [ ] https://github.com/restatedev/restate/issues/923
- [ ] https://github.com/restatedev/sdk-java/issues/174
- [ ] https://github.com/restatedev/sdk-typescript/issues/193
```

**Comment by tillrohrmann** [comment]
Shall we update this issue to let side effects wait for any in flight journal entry instead?

**Comment by tillrohrmann** [comment]
Closing because this issue is not needed atm.
