### ISSUE TITLE
Cancel invocations by cancelling from the leaves

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#978]
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/restate/issues/986
- [ ] restatedev/restate#943
- [ ] https://github.com/restatedev/restate/issues/996
- [ ] https://github.com/restatedev/e2e/issues/228
- [ ] https://github.com/restatedev/restate/issues/1029
- [ ] https://github.com/restatedev/documentation/issues/233
- [ ] https://github.com/restatedev/examples/issues/52
```

**Comment by tillrohrmann** [comment]
Finished this effort.
