### ISSUE TITLE
Implement key extraction for grpc messages

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#98]
This issue is an umbrella issue to keep track of the efforts to implement key extraction for grpc messages.

```[tasklist]
### Tasks
- [ ] #87 
- [ ] https://github.com/restatedev/restate/issues/239
- [ ] https://github.com/restatedev/restate/issues/240
- [ ] https://github.com/restatedev/restate/issues/250
- [ ] https://github.com/restatedev/restate/issues/251
```
